server:
  port: 8001
spring:
  application:
    name: customer-service
  datasource:
      #url: jdbc:h2:mem:customer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      #username: customer
      #password: customer
      #driver-class-name: org.h2.Driver
      #url: jdbc:mysql://localhost:3306/onlineretailstore
      #driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mydatabase.clgwgw628igj.us-east-1.rds.amazonaws.com:3306/onlineretailstore
      username: orsuser
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
#create database onlineretailstore;
#create user orsuser;
#grant all privileges on onlineretailstore.* to orsuser;
#below credentials of AWS RDS
#username: admin
#password: adminpassword

