server:
  port: 8002
spring:
  application:
    name: product-service
  datasource:
        url: jdbc:mysql://localhost:3306/onlineretailstore
        username: orsuser
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update