server:
  port: 8000
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8001
          predicates:
            - Path=/ors/api/v1/customers/**
        - id: product-service
          uri: http://localhost:8002
          predicates:
            - Path=/ors/api/v1/products/**
        - id: order-service
          uri: http://localhost:8005
          predicates:
            - Path=/ors/api/v1/orders/**
        - id: cart-service
          uri: http://localhost:8004
          predicates:
            - Path=/ors/api/v1/cart/**
        - id: inventory-service
          uri: http://localhost:8003
          predicates:
            - Path=/ors/api/v1/inventory/**
