server:
  port: 8005
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/onlineretailstore
    username: orsuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


