server:
  port: 8004
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/onlineretailstore
    username: orsuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect